# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jungbin's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll

include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5

plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
    title: Portfolio

author:
  name             : "Jungbin Kim"
  email            : "mail@jungbin.kim"
  bio              : "I'm interested in virtual reality(VR), augmented reality(AR), programming."
  github           : "jungbin-kim"
  linkedin         : "jungbin-kim"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      sidebar:
        nav: "posts"
      comments: true
  # _pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true

google_analytics: "UA-107842956-1"

comments:
  provider: "disqus"
  disqus:
    shortname: "blog-jungbin-kim"

